// <auto-generated />
using System;
using CRMVentasAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRMVentasAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251020021151_IntegracionClientesExternos")]
    partial class IntegracionClientesExternos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CRMVentasAPI.Models.CondicionComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClienteId")
                        .HasColumnType("longtext");

                    b.Property<double>("DescuentoPorcentual")
                        .HasColumnType("double");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("OportunidadId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioEspecial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioUltimaActualizacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CondicionesComerciales");
                });

            modelBuilder.Entity("CRMVentasAPI.Models.DescuentoAplicado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteId")
                        .HasColumnType("longtext");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CondicionComercialId")
                        .HasColumnType("int");

                    b.Property<double>("DescuentoPorcentual")
                        .HasColumnType("double");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OportunidadId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PropuestaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAplicacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DescuentosAplicados");
                });

            modelBuilder.Entity("CRMVentasAPI.Models.Embudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Etapas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCierreProbable")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProbabilidadCierre")
                        .HasColumnType("int");

                    b.Property<double>("ValorEstimado")
                        .HasColumnType("double");

                    b.Property<string>("Vendedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Embudos");
                });

            modelBuilder.Entity("CRMVentasAPI.Models.Oportunidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCierreProbable")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Vendedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Oportunidades");
                });

            modelBuilder.Entity("CRMVentasAPI.Models.Propuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OportunidadId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OportunidadId");

                    b.ToTable("Propuestas");
                });

            modelBuilder.Entity("CRMVentasAPI.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OportunidadId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OportunidadId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("CRMVentasAPI.Models.Propuesta", b =>
                {
                    b.HasOne("CRMVentasAPI.Models.Oportunidad", "Oportunidad")
                        .WithMany("Propuestas")
                        .HasForeignKey("OportunidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oportunidad");
                });

            modelBuilder.Entity("CRMVentasAPI.Models.Tarea", b =>
                {
                    b.HasOne("CRMVentasAPI.Models.Oportunidad", "Oportunidad")
                        .WithMany("Tareas")
                        .HasForeignKey("OportunidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oportunidad");
                });

            modelBuilder.Entity("CRMVentasAPI.Models.Oportunidad", b =>
                {
                    b.Navigation("Propuestas");

                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
